language: node_js
node_js:
  - "7"
install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
- npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script: npm run build:modules && npm run build && npm run-script test-on-travis
